# 状態:
# 1: 新品、未使用, 2: 未使用に近い, 3: 目立った傷や汚れなし,
# 4: やや傷や汚れあり, 5: 傷や汚れあり, 6: 全体的に状態が悪い

ターゲット:

  - 検索:         [Oculus Rift]
    除外:         "DK[12]"
    価格:         [0, 70000]
    ページ数:     5

  - 検索:         [GTX1080, GTX980]
    カテゴリ:     [7/96/1156] #  家電・スマホ・カメラ/PC・タブレット/PCパーツ
    除外:         GTX ?(10[765]0|9[765]0|8.0|7.0)
    除外カテゴリ: "デスクトップ型PC|雑誌|本"
    価格:         [10000, 90000]
    状態:         [1, 2, 3]
    ページ数:     5

ブラックリスト:
  - 123456789

通知メール:
  to: me@example.com
  type: 2
